language: go
go: 1.8
sudo: false
dist: trusty
before_install:
- go get github.com/mattn/goveralls
install:
- go get github.com/BurntSushi/toml
- go get github.com/go-kit/kit/log
script:
- goveralls -service=travis-ci -package=.
env:
  global:
  - VERSION=$(cat VERSION)
before_deploy:
- mkdir -p release
- GOOS=linux  GOARCH=amd64 go build -o release/samlare-v$VERSION-linux-amd64
- GOOS=darwin  GOARCH=amd64 go build -o release/samlare-v$VERSION-darwin-amd64
deploy:
  provider: releases
  api_key:
    secure: AtTrfGGDMwD0GwyxLSul7vjarMtsT3sTjBZ9FGoErjUanlAwcHrSYWqsKcfFa5MOacabQdduAoPCUT9li3z43W+mlgx1Jzh8Le/4/j5q5Pxav4bapCRgqto5xl69w2zlioZ7g3wcs9Ycr+OypbQ0F8xgdN0kYSXdhsjakrRqcPlxpql8JVOjhNo/bX3TBrR2vVV74dBH/aYAfeOBZyJI7AMxfPXUX7W/Nq57/nJMPmU63nTJUVbpsddg6a5CmNx238ejayZimw1Ka8cPJHyYn61h+ATYtBRZj3yefD2kbFKkwjICD+HeqtiObwBF6r2nygZ1p+EORL/QgPnqsHMZQMLZoGJcFW2KchaADGE2VuIOSRYGQLF+GgAXAFm4ci7/5kCOMirn5SQ59OylzaVyDDeQ1e0DJ0xkr/cPa4Aze/LgTIJq1w6JAtfbWAcKRArWFV8Ftha+4PubmrKOKUxgDIh1g2Acy8n2LnNV0H0fgMP/noaHZi8XTUVeZrI6NDkoybLFNjOIJSktKPXUms75dTezcTB5oWXxCt6K/PlVmJIejcOLA6dAuBaHQQzQAk+ojMlyGAcUsJ83ybfQJ/Dzg69d6QTiTSOK5mFEhue8rKrm1UagoiqjPj4ZlKwB6l6A/XlZscjCvgUXLT/cQ7y8NHtRJ9ErRYy8pQ7aaJN3f44=
  file:
  - release/samlare-v$VERSION-linux-amd64
  - release/samlare-v$VERSION-darwin-amd64
  skip_cleanup: true
  on:
    tags: true
