language: go
go: 1.8
sudo: false
dist: trusty

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get github.com/BurntSushi/toml
  - go get github.com/go-kit/kit
  
script:
  - goveralls -service=travis-ci -package=.
