language: go
go: 1.8
sudo: false
dist: trusty
before_install:
- go get github.com/mattn/goveralls
install:
- go get github.com/BurntSushi/toml
- go get github.com/go-kit/kit/log
script:
- goveralls -service=travis-ci -package=.
env:
  global:
  - VERSION=$(cat VERSION)
  - secure: ocGnTEaS1IZ88ikXABtV4Rgik356PCYsbe8WWWpW4wAma7RnLrr2hxmRrEnJj7XXgupxGj0scKPOeYOMpbWvOY7+ZJCDVuwDXV4m9dDdhcutD7CUGPeu4PdLZOBx9CsSdY3xdKDagCY+zlgPLCIY9z7ajZfwBecQzy3dWBlYfFHbJDFmA3hnlcDJoicYGTaBd8/axZsJihAIO/+FQtWWPoB0PK+5W2gcRIpAOsOW7/AWwoLVmvyZbqv5tIYp1O1khk270ZVIlIKQMoPyOxvwhSDBuvFnILjPIsEGkQsECLbGxWlEk7YF+I7N6UeEwQInsTJFn8toOk67hifd1MrgEjfJb3C/EbMDJQjIDjfxDhe9PDb1gqcUQGfN9HvUa9GFF2jRdCzNZGrC8sC5obhQM/S6/W76+qiR1ppDx4Ogq3fklnbGq59n0NKv0zkb6JS+avZpCt1jc3T4B+EcPKrD3BhDOM4RfkEK4N5AGadtYSN1J3gz8PB7rLziS4rgMgUCtYDv0DSAUted/0G4/7dn3b+KyvF2BniEOCDP5bFngfHcqaqPf/cA36nmpk8gUxxHtSu4o8Mntex0jl9+tj80KKa9T5C13YYR4ByRYUvTN9c8Ic40ZVtUkdC9HlTKfifqb0tjkOAgY99zD/2jLrpYB8+gsNLPQAZRg7N6EuVcSks=
  - secure: GMzELB6yauiC3QKdOr+SydwGgxGroxAnepLAuJnnyRUq5wY1RErVU93luNNbMslvxm70zQBYIo0Mxby6iDpq8J70B1s/5yZ7ODL4mKzbtFUamcKYrfpQoguFAHz+gAKNTUFmm9ozeNzZsHgbu+S9pmbqewiZBJdMiyeO2/99UfMKLgOt5ML0d4aKfWGZynB1MIm0a69YPPMDwRwi/01gWQfAyWVUxweyGOQbCGTNqQl8HFGQhGL0BZXZ7c5DMOELFOA+0tpH0/C7n4sGyFqDpXMF0WdVdI/CO8aJSyFbdeilnXLotHHwyNEE8PtCKtNIenbFtbGvJL+c9kakRWubYqskHQwDTSC+bKef/CcO17QiuhrxSM8Jjx6Bgb5flpaG1modsOreyKSc1ogw8m34JMHLWjN4w7HylVyMUMzWw+AjJUk0gvKV0xbJhUDAQb40IEgD9v6gK2uWYRIhmy5jYSu3F20PLJr5BOasm0Ua18qm0PVbDFdQz2FcgK7/WPYRw4iKHUk6IflhHnqZb0SUwTNGnxNkazq3Z+R5Kei+0TJnjpVGtz4lE6I91TAm+QmHXjfeToIKJu4FcT3JIoxW+/uBM4U8FrCv4mTpxgSx4KnAL2q544vWZoU5b8EbZkoZ8ND2TziBmSiPX45D13SyM73btwuZNXpPvgFQjI+tk0o=
  - secure: f8muJOpYCwcMMBmc8UmmWYNvDX2Vcy3A9uCh5GAdqD/q/U/7JTPCcVuBhNfgsNsPEnaRWAivXZOJWQ2gBY3P77XxP2eoXgxgRrRwJLv/jw5UEzzAEVum2lVff/JW8KuUk+O4461AXLNFwr+jrwpJ5/xFrd9EEOXXyPOQ6MYFHSELHtMGrsz1zvIvJryIErBkqIBwybi1VjgqmU4EILA40coyANg6fK3TuHoYkZU4nJAotRJqUi+km7dw6tm0NMD+aekWWhNDlnP97AcfgMofJoOX0GbGV6US5+3y8e29oC96vOAvHDHR13LjkJ/1jPlRNHNY+jqi0fWiED6TSUtMsn8Nhk1mqgqEu5vXIQTsUr+JUVHXjsSygPAf9dnL1GtwfPTYRZUt9Sd7/0QAs7g4KvENsSZxmFENG/k1fMq3T0n1HlgF9iHikI7YVtoW/1Tw2H5eVvPJLqT4ksDVDYQOkdwXkDuD4VYWRpHABxBl9MS3GbHUg1MS5onMMk28tVKJCyenZ98zqOqTYrIIKmDPHePFAatiYo8kLd133kTiqdu+CYc4AFck5Lv269lYnGciCP/5ZCeOzGBeZUQVRn3iAs9J2hgJQgOgjJY2xuF85GTJdXRf90LP1P7CC+loZL5Q3C2XLSxU3HVCk+As3oZ7s5WG51GL0ewDfAtzvHwvrho=
  - secure: pMXEgZECdBXVCul1LoCW/tVrjCtZxCHR43pB/YNvb18qzynQntCAxFLGUMJd++QkSXIFnZktOwNOEABYCCsnL0gj2NIKbVP0dG2iCVBZ8T5apLdaTsIXF91RSQV/OEKhV0wMyzPWRA2DJrWWQPoOuDdMZqPZMszwQ0Nig0JOIyPRoUCU0Hc2c0yNSkFT6mTBVR9fWetvIqZ3DI2bkQ9pMTo1a8YjEyYfraXr1MfDXgmkk/zOW02dzwNj8HJyq/oeQ/AXcwPkdB4dRm1zgwORbZ4wQ7Pg/dwqpvXP4MibKwzqKBsqYApcd7im91dTGmgMZ8Po8SFJLughWyCi6BOmwYe/uJaJBKjLHZMJxQJO8Taeu2K4Dne6unsT5lQb8wcXpu3z1vADyW84dTpBMRB87f41Jwx1MGeqeZncomHVGBtEy7a+E5tH3WnRXlEbbm9tKv2RhJacJRzcaNUYXKmiMCzAWQ/fX3QVJiEAgAnY798pYlum4kCub0AOySbGmunjRHHLPqNdcP9IZzI6ZuGsNH69ZHXmiKvG9prtK+xjb3F5H6Hwx7zT0++goEVI0yh63vRHFZr7unURyvkG0+e2RN31bWbnqEnlJqWvBeRk2L/4fzW7H37Y3Hf8wkHSmzpbvPA+AE9pP1WVdazGGAP6VNWKri5vjux5Usnzu4ZTSXY=
before_deploy:
- mkdir -p release
- GOOS=linux  GOARCH=amd64 go build -o release/samlare-v$VERSION-linux-amd64
- GOOS=darwin  GOARCH=amd64 go build -o release/samlare-v$VERSION-darwin-amd64
deploy:
  provider: releases
  file:
  - release/samlare-v$VERSION-linux-amd64
  - release/samlare-v$VERSION-darwin-amd64
  skip_cleanup: true
  on:
    tags: true
