* samlare

Samlare (it means "collector/gatherer" in swedish) is a simple tool
for collecting data from expvar endpoints and submitting it to
graphite.

** Installation

It's available for Linux as a plain binary (other platforms coming
soon). Download it from the releases and put it in your path.

Docker image also coming soon.

** Configuration

The only commandline argument it takes is a path to a config file (it
will default to looking for ~/etc/samlare/config.toml~ if you don't
specify a path):

#+BEGIN_EXAMPLE
$ samlare -config=/path/to/my/config.toml
#+END_EXAMPLE

That's a TOML file with a fairly simple format.

A simple example is included (see ~sample-config.toml~) and looks
something like:

#+BEGIN_SRC toml
CarbonHost = "graphite.example.com"
CarbonPort = 2003
CheckInterval = 60
Timeout = 3000

[endpoints]

  [endpoints.app1]
        URL = "http://localhost:14001/debug/vars"
        Prefix = "apps.app1"

  [endpoints.app2]
        URL = "http://localhost:14002/debug/vars"
        Prefix = "apps.app2"
#+END_SRC

The top level fields that need to be set are:

- ~CarbonHost~ -- hostname/ip of your carbon server
- ~CarbonPort~ -- port for your carbon server
- ~CheckInterval~ -- how many seconds between checks
- ~Timeout~ -- max milliseconds to wait for a response from each
  endpoint

Then you have a stanza for each endpoint that you want to watch.

Each requires

- ~URL~ -- the full URL of the endpoint
- ~Prefix~ -- the graphite metric prefix to use

~CheckInterval~ and ~Timeout~ can also be individually overridden for
each endpoint as well.

** Additional Features

Samlare will respond to a ~SIGHUP~ signal by reloading its config
file. This is particularly handy if you use something like
consul-template to generate your config file automatically.
